# Fichier de configuration générique (à adapter au projet)
dataset:
  name: "zh-plus/tiny-imagenet"                # ex: "CIFAR10", "IMDB", ...
  root: "./data"            # chemin local pour les données
  split:                    # optionnel : noms/tailles de splits
    train: "train"
    val: 8000
    test: 2000
  download: true            # si supporté
  num_workers: 2
  shuffle: true

preprocess:
  # transformations de base (ex: resize, normalize)
  resize: [64, 64]                 # ex: [32, 32] ou null
  normalize:          
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]       # ex: {"mean": [0.5,0.5,0.5], "std":[0.5,0.5,0.5]} ou null
  text_tokenizer:           # pour NLP : nom ou paramètres, sinon null

augment:
  # data augmentation (laisser null si non utilisée)
  random_flip: true            # true/false
  random_crop:       
    size: 64
    padding: 4       # paramètres ou null
  color_jitter:    
    brightness: 0.1
    contrast: 0.1
    saturation: 0.1
    hue: 0.02         # paramètres ou null


model:
  type: "inception_multibranch"               # ex: "resnet18", "mlp", "lstm", ...
  num_classes: 200
  input_shape: [3, 64, 64]
  num_modules: 6
  branch_channels: [64, 64, 64]         # ex: [3, 32, 32] ou null
  hidden_sizes: null             # ex: [256, 128] ou null
  activation: relu          # ex: relu, gelu, tanh...
  dropout: 0.0              # ex: 0.0–0.5
  batch_norm: true         # true/false
  residual: false           # true/false
  attention: false          # true/false
  rnn: null                      # pour RNN/LSTM/GRU : paramètres ou null

train:
  seed: 42
  device: auto              # "cpu", "cuda", ou "auto"
  batch_size: 32
  epochs: 40
  max_steps: null           # entier ou null
  overfit_small: false 
  overfit_size: 32     # true pour sur-apprendre sur un petit échantillon

  optimizer:
    name: adam              # sgd/adam/rmsprop
    lr: 0.001
    weight_decay: 0.00001
    momentum: 0.9           # utile si SGD

  scheduler:
    name: none              # none/step/cosine/onecycle
    step_size: 10
    gamma: 0.1
    warmup_steps: 0

metrics:
  classification:           # ex: ["accuracy", "f1"]
    - accuracy
  regression: []            # ex: ["mae", "rmse"]

hparams:          
  epochs: 2          # espace pour mini grid search
  lr: [0.0001, 0.001, 0.002]
  batch_size: [32, 64]
  weight_decay: [0.00001, 0.0001]
  num_modules: [4, 6]
  branch_channels:
    - [64, 64, 64]
    - [48, 72, 72]
  tag: "grid_search"

paths:
  runs_dir: "./runs/train_model2"
  artifacts_dir: "./artifacts"
